# Generated by Django 6.0.5 on 2026-05-16 21:01

from django.db import migrations, models


def publish_existing_entries(apps, schema_editor):
    Entry = apps.get_model('entries', 'Entry')
    Entry.objects.update(is_published=True)


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(publish_existing_entries, migrations.RunPython.noop),
    ]
