# Generated by Django 6.0.5 on 2026-06-06 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_book_person_entry_book_book_author_entry_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('source_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='entries.entry')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='entries.person')),
            ],
            options={
                'ordering': ['entry', 'order'],
            },
        ),
    ]
